spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasks
      username: root
      password: rootpassword
      authentication-database: admin
      auto-index-creation: true
